### ISSUE TITLE
zlib error

### ISSUE THREAD

**Issue by vangjin** [Jarvis73/FPTrans#5]
When I followed your steps to configure the environment and run the code, the following error occurred：
```
Traceback (most recent call last):
  File "/home/wj/.local/lib/python3.8/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/home/wj/.local/lib/python3.8/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/home/wj/.local/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/home/wj/.local/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "run.py", line 99, in train
    trainer.start_training_loop(start_epoch, evaluator, num_classes)
  File "/home/wj/code/FPTrans/core/base_trainer.py", line 281, in start_training_loop
    for i, batch in enumerate(gen, start=1):
  File "/home/wj/.local/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/wj/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/wj/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/wj/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/wj/.local/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
zlib.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/wj/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wj/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wj/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wj/code/FPTrans/data_kits/voc_coco.py", line 298, in __getitem__
    kwargs['weights'] = self.get_weights(weight_path, cls)
  File "/home/wj/code/FPTrans/data_kits/voc_coco.py", line 263, in get_weights
    cache_weights[name] = load_weights(data_dir / name)
  File "/home/wj/code/FPTrans/utils_/misc.py", line 36, in load_weights
    edts = npzfile['x']
  File "/home/wj/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 249, in __getitem__
    magic = bytes.read(len(format.MAGIC_PREFIX))
  File "/usr/lib/python3.8/zipfile.py", line 940, in read
    data = self._read1(n)
  File "/usr/lib/python3.8/zipfile.py", line 1016, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid distance too far back


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 193, in <module>
    ex.run_commandline()
  File "/home/wj/.local/lib/python3.8/site-packages/sacred/experiment.py", line 347, in run_commandline
    print_filtered_stacktrace()
  File "/home/wj/.local/lib/python3.8/site-packages/sacred/utils.py", line 493, in print_filtered_stacktrace
    print(format_filtered_stacktrace(filter_traceback), file=sys.stderr)
  File "/home/wj/.local/lib/python3.8/site-packages/sacred/utils.py", line 528, in format_filtered_stacktrace
    return "".join(filtered_traceback_format(tb_exception))
  File "/home/wj/.local/lib/python3.8/site-packages/sacred/utils.py", line 568, in filtered_traceback_format
    current_tb = tb_exception.exc_traceback
AttributeError: 'TracebackException' object has no attribute 'exc_traceback'
```
How to solve this problem? The same problem still occurs after I use command 'pip install --upgrade setuptools' to update.

**Comment by Jarvis73** [comment]
It seems the loss weights are not correctly parsed. Do you use the provided pascal_weights/coco_weights zip file? 

Try to regenerate in your current python environment following the [instructions (option 2)](./data/README.md).

**Comment by pur-suit** [comment]
I tried option 2, but l encounter zlib error
